/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - To understand data distribution across categories.

SQL Concepts Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/

-- ============================================================================
-- Total customers by country
-- ============================================================================
SELECT
    country,
    COUNT(DISTINCT customer_key) AS total_customers
FROM 
    gold.dim_customers
GROUP BY 
    country
ORDER BY 
    total_customers DESC;


-- ============================================================================
-- Total customers by gender
-- ============================================================================
SELECT
    gender,
    COUNT(DISTINCT customer_key) AS total_customers
FROM 
    gold.dim_customers
GROUP BY 
    gender
ORDER BY 
    total_customers DESC;


-- ============================================================================
-- Total products by category
-- ============================================================================
SELECT
    category,
    COUNT(DISTINCT product_key) AS total_products
FROM 
    gold.dim_products
GROUP BY 
    category
ORDER BY 
    total_products DESC;


-- ============================================================================
-- Average product cost per category
-- ============================================================================
SELECT
    category,
    AVG(product_cost) AS avg_cost
FROM 
    gold.dim_products
GROUP BY 
    category
ORDER BY 
    avg_cost DESC;


-- ============================================================================
-- Total revenue by product category
-- ============================================================================
SELECT
    p.category,
    SUM(f.sales_amount) AS total_revenue
FROM 
    gold.fact_sales f
LEFT JOIN 
    gold.dim_products p ON f.product_key = p.product_key
GROUP BY 
    p.category
ORDER BY 
    total_revenue DESC;


-- ============================================================================
-- Total revenue generated by each customer
-- ============================================================================
SELECT
    c.first_name + ' ' + c.last_name AS customer_name,
    SUM(f.sales_amount) AS total_revenue
FROM 
    gold.fact_sales f
LEFT JOIN 
    gold.dim_customers c ON f.customer_key = c.customer_key
GROUP BY 
	c.first_name, c.last_name
ORDER BY 
    total_revenue DESC;


-- ============================================================================
-- Distribution of sold items across countries
-- ============================================================================
SELECT
    c.country,
    SUM(f.quantity) AS total_quantity_sold
FROM 
    gold.fact_sales f
LEFT JOIN 
    gold.dim_customers c ON f.customer_key = c.customer_key
GROUP BY 
    c.country
ORDER BY 
    total_quantity_sold DESC;
